// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/admin/api": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description"
                "description": "更新API信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API模块"
                ],
                "summary": "更新API",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.ApiUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
                }
            },
        "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description"
            "post": {
                "description": "创建新的API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API模块"
                ],
                "summary": "创建API",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.ApiCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
                }
   "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "
            },
            "delete": {
                "description": "删除指定API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API模块"
                ],
                "summary": "删除API",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "API ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
                }
            }
    "security": [
                    {
                        "Bearer": []
                    }
                ],
             
        },
        "/v1/admin/apis": {
            "get": {
                "description": "获取API列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API模块"
                ],
                "summary": "获取API列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API分组",
                        "name": "group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "API名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "API路径",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "请求方法",
                        "name": "method",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.GetApisResponse"
                        }
                    }
                }
                "security": [
                    {
                        "Bearer": []
                    }
   
            }
        },
        "/v1/admin/menu": {
            "put": {
                "description": "更新菜单信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单模块"
                ],
                "summary": "更新菜单",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.MenuUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
        "post": {
                "security": [
                    {
                        "Bearer": []
          
                    }
                }
            },
            "post": {
                "description": "创建新的菜单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单模块"
                ],
                "summary": "创建菜单",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.MenuCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
     },
            "delete": {
                "security": [
                    {
                        "Bearer": [
                    }
                }
            },
            "delete": {
                "description": "删除指定菜单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单模块"
                ],
                "summary": "删除菜单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜单ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/admin/menus": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取管理员菜单列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单模块"
                ],
                "summary": "获取管理员菜单",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.GetMenuResponse"
                        }
                    }
                }
/admin/role": {
            "put": {
                "security": [
                    {
                        "
            }
        },
        "/v1/admin/role": {
            "put": {
                "description": "更新角色信息",
                "consumes": [
                    "application/json"
                ],
                    "application/json"
                ],
                "tags": [

                    "角色模块"
                ],
                "summary": "更新角色",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
body",
                        "required"
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.RoleUpdateRequest"
                        }
                ],
                    "用户模块"
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
"
                        }
                    }
                }
            },
            "post":
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色模块"
                ],
                "summary": "创建角色",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.RoleCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                 "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
   
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色模块"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                ],
                        "description": "角色ID",
                        "name": "id",
                        "description": "OK",
                        "schema": {
                "summary": "获取用户信息",
                "responses": {
                    "200": {
"description": "OK",
                       
                        "description": "OK",
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
        }
                    }
                }
            }
        },
        "/v1/admin/role/permi
                    }
                }
            }
        },
        "/v1/admin/role/permissions": {
            "get": {
                "description": "获取指定角色的权限列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限模块"
                ],
                "summary": "获取角色权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色名称",
                        "name": "role",
                   "name": "role",
   
                        "required": true
                    }
uired": true
                    }
              
 ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Ge
                ],
                "responses": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.GetRolePermissionsData"
                            "$ref": "#/definitions/github_com_go-nunu_nunu-layout-advanced_api_v1.GetProfileResponse"
                        }
                    }
            "put": {
                "description": "更新指定角色的权限列表",
                "consumes": [
                    "application/json"
            },
    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限模块"
                ],
                "summary": "更新角色权限",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.UpdateRolePermissionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
finitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/admin/roles": {
            "get": {
                "security": 
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/admin/roles": {
            "get": {
                "description": "获取角色列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色模块"
                ],
                "summary": "获取角色列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "角色ID",
                        "name": "sid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "角色名称",
                        "name": "name",
            "get": {
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.GetRolesResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/user": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
     "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Get
                "tags": [
                    "用户模块"
                ],
                "summary": "获取管理用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.GetAdminUserResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "更新管理员用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "更新管理员用户",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.AdminUserUpdateRequest"
                        }
        "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
                }
            }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的管理员用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "创建管理员用户",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.AdminUserCreateRequest"
                        }
"#/definitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
                }
            },
            "d
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定管理员用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "删除管理员用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/admin/user/permissions": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取当前用户的权限列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限模块"
                ],
layout-admin_api_v1.GetUserPermissionsData"
                        }
                    }
                }
            }
        },
        "/v1/admin/users": {
            "
                "summary": "获取用户权限",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.GetUserPermissionsData"
                        }
                    }
                }
            }
        },
        "/v1/admin/users": {
            "get": {
                "description": "获取管理员用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "获取管理员用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "昵称",
                        "name": "nickname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query"
            }
        },
        "/v1/login": {
            "post": {
                "consumes": [
                    "application/json"
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.GetAdminUsersResponse"
                        }
                    }
                }
"application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "账号登录",
                "parameters": [
                    {
                }
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.LoginResponse"
                        }
                    }
          
            }
        },
        "/v1/menus": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取当前用户的菜单列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单模块"
                    "200": {
                        "description": "OK",
                "username"
            ],
            "properties": {
                            "$ref": "#/definitions/nunu-layout-admin_api_v1.GetMenuResponse"
                        }
                    }
                "
                }
            }
        }
    },
    "definitions": {
        "nunu-layout-admin_api_v1.AdminUserCreateRequest": {
            "type": "object",
",
                "username"
            ],
            "required": [
                "password",
                "email": {
                "email": {
                    "type": "string",
                    "example": "1234@gmail.com"
                "nickname": {
                    "type": "string",
                    "example": "小Baby"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "type": "string",
                    "example": "1858888888"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        ""
                    ]
                },
                "username": {
                    "type": "string",
                    "example": "张三"
                }
            }
        },
        "nunu-layout-admin_api_v1.AdminUserDataItem": {
                "nickname",
                "password",
              "type": "string"
                },
                "em
                "username"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "1234@gmail.com"
                },
                "id": {
            "properties": {
                "code": {
                "nickname": {
                    "type": "integer"
                },
                },
                "password": {
                    "type": "string",
                "roles": {
   },
                "roles": {
                    "type": "array",
                    "items": {
                }
            }
        },
        "nunu-layout-admin_api_v1.AdminUserUpdateRequest": {
                    },
                    "example": [
  },
                "updatedAt": {
                    "type": "st
                        ""
                    ]
                },
                "updatedAt": {
                },
          },
                "username": {
                    "type": "string"
                    "type": "string",
                "message": {
                    "type": "string"
                "password": {
         "required": [
    },
        "nunu-layout-admin_api_v1.
                "username"
            "type": "object",
            "required": [
                },
                    "type": "string",
                    "example": "1234@gmail.com"
                    "items": {
                "id": {
                    "type": "integer"
                },
                "nickname": {
             
                    "example": "小Baby"
                },
                    "type": "string",
                    "type": "string",
e": "string",
                    "example": "1858888888"
                },
                "roles": {
                    "type": "array",
                    "items
                    
                "roles": {
                    "type": "array",
                },
                        "type": "string"
                    },
                    "example": [
                        ""
                    ]
                },
                "username": {
                    "type": "string",
                    "example": "张三"
            "properties": {
                "nickname": {
                    "type": "string",
                }
            }
        },
                "group": {
                    "type": "string",
                    "example": "权限管理"
                },
                "method": {
                    "type": "string",
                    "example": "GET"
                },
                "name": {
                    "type": "string",
                    "example": "菜单列表"
                },
                "path": {
                    "type": "string",
                    "example": "/v1/test"
                }
            }
        },
        "nunu-layout-admin_api_v1.ApiDataItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "method": {
                "id"
                },
                "name": {
                    "type": "string"
pe": "string"
                },
                "path": {
                    "t
                },
                "path": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "nunu-layout-admin_api_v1.ApiUpdateRequest": {
                },
                "userId": {
                "id"
            "type": "object",
            "required": [
            "group": {
            ],
            "properties": {
                "group": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "method": {
                    "type": "string",
                    "example": "GET"
                },
                "name": {
                    "type": "string",
                    "example": "菜单列表"
                },
                "path": {
                    "type": "string",
                    "example": "/v1/test"
                }
            }
        },
        "nunu-layout-admin_api_v1.GetAdminUserResponse": {
            "type": "object",
                },
                "data": {
                    "$ref": "#/definitions/nunu-layout-admin_api_v1.GetAdminUserResponseData"
                },
_v1.GetAdminUserResponseData"
                },
                "message": {
     
            }
        },
        "nunu-layout-admin_api_v1.GetAdminUserResponseData": {
            "type": "object",
erResponseData": {
            "type": "object",
            "properties": {
                "c
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                   
        "github_com_go-nunu_nunu-layout-advanced_api_v1.LoginRequest": {
                  "type": "integer"
                    "example": "1234@gmail.com"
                },
                "id": {
                    "type": "integer"
                    "example": "小Baby"
               
            "type": "object",
            "required": [
                },
             "type": "string"
                "password": {
                "roles": {
            "properties": {
                    "items": {
                        "type": "string"
                    },
                    "example": [
                    "$ref": "#/definitions/nunu-layout-admin_api_v1.GetAdminUsersResponseData"
                    ]
                },
                "updatedAt": {
": "string"
                },
                "usernam
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "张三"
                }
            }
        "nunu-layout-admin_api_v1.GetAdminUsersResponse": {
        "nunu-layout-admin_api_
            ],
        },
        "nunu-la
            "type": "object",
                    "type": "string",
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "string",
                },
                "message": {
                    "type": "string"
        },
        "nunu-layout-admin_api_v1.GetAdminUsersResponseData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nunu-layout-admin_api_v1.AdminUserDataItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "nunu-layout-admin_api_v1.GetApisResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/nunu-layout-admin_api_v1.GetApisResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "nunu-layout-admin_api_v1.GetApisResponseData": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nunu-layout-admin_api_v1.ApiDataItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "nunu-layout-admin_api_v1.GetMenuResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/nunu-layout-admin_api_v1.GetMenuResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "nunu-layout-admin_api_v1.GetMenuResponseData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nunu-layout-admin_api_v1.MenuDataItem"
                    }
                }
            }
        },
        "nunu-layout-admin_api_v1.GetRolePermissionsData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "nunu-layout-admin_api_v1.GetRolesResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/nunu-layout-admin_api_v1.GetRolesResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
                }
            }
        },
        "nunu-layout-admin_api_v1.LoginRequest": {
            "type": "object",
            "required": [
                    }
                },
            ],
            "properties": {
                "password": {
                    "type": "integer"
                }
          "type": "integer"
                }
            }
        },
        "nunu-layout-admin_api_v1.GetUserPermissionsData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "nunu-layout-admin_api_v1.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "1234@gmail.com"
                }
            }
        },
        "nunu-layout-admin_api_v1.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/nunu-layout-admin_api_v1.LoginResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "nunu-layout-admin_api_v1.LoginResponseData": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                }
            }
        },
        "nunu-layout-admin_api_v1.MenuCreateRequest": {
            "type": "object",
            "properties": {
                "component": {
                    "description": "绑定的组件",
                    "type": "string"
                },
                "hideInMenu": {
                    "description": "是否保活",
                    "type": "boolean"
                },
                "icon": {
                    "description": "图标，使用字符串表示",
                    "type": "string"
                },
                "keepAlive": {
                    "description": "是否保活",
   
            }
        },
        "nunu-layout-admin_api_v1.GetUserPermissionsData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
        "nunu-layout-admin_api_v1.MenuDataItem": {
            "type": "object",
            "properties": {
                "component": {
                    "description": "绑定的组件",
                    "type": "string"
                },
                "hideInMenu": {
                    "description": "是否保活",
                    "type": "boolean"
                },
                "icon": {
                    "description": "图标，使用字符串表示",
                    "type": "string"
                },
                "id": {
                    "description": "唯一id，使用整数表示",
                    "type": "integer"
                },
                "keepAlive": {
                    "description": "是否保活",
                    "type": "boolean"
                },
                "locale": {
                    "description": "本地化标识",
                    "type": "string"
                },
                "name": {
                    "description": "同路由中的name，唯一标识",
                    "type": "string"
                },
                "parentId": {
                    "description": "父级菜单的id，使用整数表示",
                    "type": "integer"
                },
                "path": {
                    "description": "地址",
                    "type": "string"
                },
                "redirect": {
                    "description": "重定向地址",
                    "type": "string"
                },
                "title": {
                    "description": "展示名称",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "是否保活",
                    "type": "string"
                },
                "url": {
                    "description": "iframe模式下的跳转url，不能与path重复",
                    "type": "string"
                },
                "weight": {
                    "description": "排序权重",
                    "type": "integer"
                }
            }
        },
        "nunu-layout-admin_api_v1.MenuUpdateRequest": {
            "type": "object",
            "properties": {
                "component": {
                    "description": "绑定的组件",
                    "type": "string"
                },
                "hideInMenu": {
                    "description": "是否保活",
                    "type": "boolean"
                },
                "icon": {
                    "description": "图标，使用字符串表示",
                    "type": "string"
                },
                "id": {
                    "description": "唯一id，使用整数表示",
                    "type": "integer"
                },
                "keepAlive": {
                    "description": "是否保活",
                    "type": "boolean"
                },
                "locale": {
                    "description": "本地化标识",
                    "type": "string"
                },
                "name": {
                    "description": "同路由中的name，唯一标识",
                    "type": "string"
                },
                "parentId": {
                    "description": "父级菜单的id，使用整数表示",
                    "type": "integer"
                },
                "path": {
                    "description": "地址",
                    "type": "string"
                },
                "redirect": {
                    "description": "重定向地址",
                    "type": "string"
                },
                "title": {
                    "description": "展示名称",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "url": {
                    "description": "iframe模式下的跳转url，不能与path重复",
                    "type": "string"
                },
                "weight": {
                    "description": "排序权重",
                    "type": "integer"
                }
            }
        },
        "nunu-layout-admin_api_v1.Response": {
                "data": {
                }
            }
        },
                    "type": "string"
                "email",
                "password"
                "password",
                "username"
                "email": {
                    "type": "string",
        "nunu-layout-admin_api_v1.RoleCreateRequest": {
                }
            }
                "name",
                "sid"
        "github_com_go-nunu_nunu-layout-advanced_api_v1.Response": {
            "type": "object",
                "name": {
                    "type": "string",
                    "example": "Admin"
                },
                "sid": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "nunu-layout-admin_api_v1.RoleDataItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "sid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "nunu-layout-admin_api_v1.RoleUpdateRequest": {
            "type": "object",
            "required": [
                "id",
                "name",
                "sid"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Admin"
                },
                "sid": {
                "code": {
                    "example": "1"
                }
            }
        },
        "nunu-layout-admin_api_v1.UpdateRolePermissionRequest": {
            "type": "object",
            "required": [
                "list",
                "role"
            ],
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        ""
                    ]
                },
                "role": {
                "message": {
                    "example": "admin"
                }
            }
        },
        "github_com_go-nunu_nunu-layout-advanced_api_v1.UpdateProfileRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "1234@gmail.com"
                },
                "nickname": {
                    "type": "string",
                    "example": "alan"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Nunu Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
